### ISSUE TITLE
Интерфейс бегунков

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#126]
По результатам обсуждения Иван-да-Марья

1. Пустые строки из бегунков убрать (либо оставить только для первого тура номинации).
2. Уменьшить высоту строки

**Comment by xfyre** [comment]
все-таки, по размышлении, оба пункта лучше оставить как есть:

1) пустые строки могут понадобиться, если прошедший в полуфинал промотался, пары уже на танцполе, и вызывают кого-то из альтернативных
2) уменьшение строки возможно только за счет уменьшения шрифта, сейчас он 12pt, что обеспечивает разумную читаемость; если сделать его меньше - будет сложнее искать
