### ISSUE TITLE
Swing & Snow - нет различий в названии евентов разных дет 

### ISSUE THREAD

**Issue by edanilov** [danceconvention/dcnet-public#169]
Что на сайте, что в приложении Swing & Snow разных лет имеет одно и тоже название. Логично было бы как у всех Swing & Snow 2015 и тп.

![](http://i.imgur.com/gfQD6C5.jpg)

**Comment by edanilov** [comment]
Правильно ли я понимаю, что это вопрос к оргам, которые вводят название евента - а не к системе?

**Comment by xfyre** [comment]
да, но я это вроде как обошел - добавив в результатах год к названию ивента 



—
