### ISSUE TITLE
Penalties and Violations features 

### ISSUE THREAD

**Issue by ofstudio** [danceconvention/dcnet-public#175]
…и логика для расчета мест при наличии оных
![screen shot 2014-12-02 at 10 41 53](https://cloud.githubusercontent.com/assets/2184504/5259353/0d0caa4e-7a10-11e4-8dad-504e5da8a5f2.png)

![screen shot 2014-12-02 at 10 42 23](https://cloud.githubusercontent.com/assets/2184504/5259356/0f4b0b34-7a10-11e4-811a-c1a56a53145e.png)

![screen shot 2014-12-02 at 10 42 48](https://cloud.githubusercontent.com/assets/2184504/5259360/1555c672-7a10-11e4-861b-79dd9a95fab6.png)

**Comment by gregbo** [comment]
The Wayne Bott Referee System contains the scoring rules for NASDE violations.

http://www.nasde.net/docs/Wayne%20Bott%20Referee%20System%20Guidance%202010.pdf
