### ISSUE TITLE
Система депозитов

### ISSUE THREAD

**Issue by roman-tik** [danceconvention/dcnet-public#19]
Реализовать возможность для участников резервировать свой пас за счет депозита (как гарантию своего участия).

Если включена эта опция в настройках ивента, то:
Пользователь видит дополнительный чекбокс под списком пасов во время регистрации
х Сделать депозит и оплатить остаток на мероприятии

если пользователь выбрал опцию, у него создается два инвойса, один из которых он оплачивает картой/пейпалом/итп, а второй на месте по прибытию.

**Comment by xfyre** [comment]
будет решено в рамках #256
