### ISSUE TITLE
Пересчет платежа в другой валюте по курсу на день оплаты

### ISSUE THREAD

**Issue by roman-tik** [danceconvention/dcnet-public#191]
В данный момент пересчет идет всех оплат с использованием текущего курса

**Comment by xfyre** [comment]
я проверил логику - на самом деле нет, все сейчас работает правильно. т.е. конвертируется по текущему курсу только текущий платеж, а уже оплаченная сумма не аффектится никак вообще.

так что это можно закрыть.
