### ISSUE TITLE
Ошибка 500 при попытке регистрации на соревнование

### ISSUE THREAD

**Issue by sashka-axis** [danceconvention/dcnet-public#195]
Попытался сейчас выполнить регистрацию на Нордкап по ссылке https://danceconvention.net/eventdirector/ru/eventprereg/181220

Выбрал «у меня нет учетной записи», в качестве номера АСХ вписал «0».
Получил HTTP ERROR 500
http://i.gyazo.com/017b0e75da3c9603d0e78bed6a741c1a.png

Какой-то набор настроек мероприятия приводит к такому?

**Comment by xfyre** [comment]
да, я это постоянно видел в exception reports, но не мог воспроизвести
сейчас попробую локально

**Comment by xfyre** [comment]
обнаружил что на нордкап зачем-то закрыли регистрацию
но ошибки при этом, конечно, не должно быть, сейчас исправлю.

**Comment by sashka-axis** [comment]
Да, регистрация была закрыта Ирой, чтобы взять паузу для обработки платежей (подробностей не знаю), но конечно ошибка должна выглядеть иначе.

**Comment by xfyre** [comment]
в течение 3 минут будет апдейт

**Comment by xfyre** [comment]
все

**Comment by sashka-axis** [comment]
Да, регистрация была закрыта Ирой, чтобы взять паузу для обработки платежей (подробностей не знаю), но конечно ошибка должна выглядеть иначе.
