### ISSUE TITLE
add billing currency override for separate signups

### ISSUE THREAD

**Issue by xfyre** [danceconvention/dcnet-public#196]
we need to be able to override default event billing currency for some registrations

**Comment by xfyre** [comment]
@Balasada I gave it some thought and this is what will be finally done.

We cannot override signup currency because we'll have a lot of complex consistency issues (specifically with statistics, but that's not the only problematic part).

However, we can easily change *user* perspective of invoice and present it to the user with any other currency. For the user, invoice amount will be converted to that currency.

Does that work for you?

**Comment by xfyre** [comment]
After final discussion we have agreed on the following:

- all priced items may be quoted in several currencies, automatic exchange rate conversion is used *only* when explicit price quote in the selected currency is not available
- billing currency for selected signups may be overridden by promoter or staff member
- user is *not* able to override currency
- if billing currency for signup is overridden, all prices are calculated and all invoices are generated in that currency
- as an option, we could make registration currency selection country-based
- all the stats, registration lists and summary data are still represented in main event billing currency

@roman-tik @Balasada the above is a summary of your requests. Please confirm we can move forward with it.

**Comment by Balasada** [comment]
Works for me!

**Comment by xfyre** [comment]
That's how it's supposed to work (screenshots from my local installation):

1) you set up additional currencies (I've simplified our initial concept and multi-currency won't be available unless you explicitly enable it - that makes it easier for events which don't need this at all)

http://monosnap.com/image/nwfrvr9WzHv5qRoH9iSFivyLX5wuu5.png

2) after you set it up, you're going to have separate price fields for each currency (example is for MultiPass, but it's the same for options and contests as well):

http://monosnap.com/image/IzY1JxMnqXGc20OehrFlTLSLoQcCx0.png

3) In each individual signup you're going to have this:
http://monosnap.com/image/Xatqk6UspH57ROqwT5G7zxOXVr9W4Y.png

When you change the currency, all prices and invoices automatically switch to the selected currency.
