### ISSUE TITLE
add country-based breakdown to stats

### ISSUE THREAD

**Issue by xfyre** [danceconvention/dcnet-public#201]

**Comment by Balasada** [comment]
Yes please! City breakdown is too detailed.

**Comment by xfyre** [comment]
This is ready and will be deployed on Monday.

**Comment by xfyre** [comment]
Done

**Comment by Balasada** [comment]
Yes, but we were thinking of it not just on the statistics page, but also on the registrations page...

**Comment by xfyre** [comment]
Another addition: make promoter comment visible in registration list popover.
