### ISSUE TITLE
Ошибка при изменении регистрации

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#208]
Изменяла партнершу у партнера, при попытке сохранить вышла ошибка, что не заполнены обязательные поля АСХ, хотя код АСХ проставлен.

Ранее таких ситуаций не возникало.

![image](https://cloud.githubusercontent.com/assets/6746669/6266874/b5326074-b84f-11e4-9258-19d8d4498937.png)

**Comment by xfyre** [comment]
не смог воспроизвести
