### ISSUE TITLE
Выгрузка результатов часть 1

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#214]
Необходимо заполнить файл common лист "регистрация ALL"

Колонки с номинациями должны содержать все РЕЙТИНГОВЫЕ номинации конкурса, а именно:
E, D, C, Абсолют, Jack’n'Jill Beginners, Rising Star, Main, Star
В строке указывается пара с данными АСХ, в колонках с номинациями ставится отметка в соответствующей номинации.
Для участников без пары в строке указывается один участник, в колонках с номинациями ставится отметка в соответствующей номинации.

Пакет с файлами скачивается по ссылке http://hustle-sa.ru/rating/konkurs.zip

**Comment by xfyre** [comment]
колонки с номинациями на главном листе я заполнять не буду (потому что они нужны в основном для учета конкурсных сборов, а это делается через систему)

остальное работает
