### ISSUE TITLE
Выгрузка результатов часть 2

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#215]
Для каждой рейтинговой номинации необходимо подготовить файл с результатами.

Формат в файлах "ггггммчч DnD импро" и "ггггммчч Класс" на листах "места" и "отчет для форума"

**Comment by xfyre** [comment]
актуальная БД АСХ где сейчас лежит? по какому адресу?

**Comment by UlianaP** [comment]
http://hustle-sa.ru/rating/ вот по этой ссылке, там есть ссылки отдельно на днд и парные, а есть ссылка на общую базу

**Comment by xfyre** [comment]
это работает как работало (файлы не обновлял, т.к. новый формат Денегина у меня не открывается корректно)
