### ISSUE TITLE
text custom attributes

### ISSUE THREAD

**Issue by xfyre** [danceconvention/dcnet-public#227]
We have one law issue more. We need to collet from users fiscal code. In italy laws are really headache. And we don't know how to ask it in comments. I think is better that the system allow the promoter to manage 1 2 or 3 custom text field. With label and mandatory flag. If you can't implement this never mind. we will not ask nothing in comments but we will ask peoples to give it at registration desk.

**Comment by xfyre** [comment]
@fcastigliego Now you have 'Custom attribute' tab in event management screen. You may add as many as you like.

**Comment by fcastigliego** [comment]
Wow!
Il 28/mar/2015 12:40 "Ilya Obshadko" <notifications@github.com> ha scritto:
