### ISSUE TITLE
Изменение политики оплаты "На месте"

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#228]
Пример. Норд кап 2015.

Участник Роман Ботвиньев, аналогично Павел Потапов
Поменяла им политику на On Spot. 

Изменилась цена за конкурс. Но сумма выставленных счетов не изменилась.

Как поступать в таких ситуациях?

Так же надо подумать как поступать, если 3 номинации оплачены заранее, а на месте захотели и оплатили еще, по новой стоимости. Что бы выставлялись сета так же по новой стоимости.

**Comment by xfyre** [comment]
Это исправлено в рамках недавнего апдейта на версию 1.4
