### ISSUE TITLE
Регистрация на месте/временная регистрация

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#229]
Пожелание/предложение

При регистрации человека "на месте", если проставляем галочку "Временная регистрация" должны появится поля "Чек ин", "Оплата", "Номер" с возможностью вывода на печать. С точки зрения процесса:
Человек точно пришел к конкурсу, с деньгами, получает номер. При этом надо его зарегистрировать, потом пойти на другие закладки проверить политики, потом в закладку оплаты, проставить платежи, потом на закладку регистрации распечатать номер. А после этого человек должен еще и зачекиниться, хотя сомнений в том что он пришел как бы нет.

**Comment by xfyre** [comment]
Это все сейчас в системе решено разными другими способами:
- есть галочка "чекин на мероприятие", которая ставится либо вручную, либо автоматически при внесении платежа во время мероприятия
- в платежи (и все изменения) можно теперь попасть из первого экрана регистрации, нет необходимости ходить по вкладкам
- в чекине на конкурсы четко видны те кто уже прошел чекин на мероприятие, поэтому тут все тоже намного проще - можно вообще не проводить процедуру чек-ина, а просто зарегистрировать всех кто пришел
