### ISSUE TITLE
Приоритет между 1 и 2

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#231]
Необходимо сделать приоритет при расчете результатов с альтернативами тем, у кого больше 1.

Для танцоров АСХ система с альтернативам вообще крайне чужда и вызывает много вопросов. Поэтому 2 считается скорее как 0,3 балла, чем как 0,5

В таком случае те, кто получил большее количество "полных" баллов, должны быть в неоспоримом приоритете перед альтернативщиками.

**Comment by xfyre** [comment]
но сейчас это именно так и работает. алгоритм устроен так:

1) отсекаем большинство по оценкам YES (1), ранжируем по критерию "у кого их больше"
2) если не добрали нужного количества - берем YES + ALT1 (1 + 2.1), ранжируем аналогично
3) повторяем шаг 2 в зависимости от того сколько у нас альтернатив
4) оставшихся ранжируем по raw score (среднеквадратичная оценка)

**Comment by xfyre** [comment]
эта задача была решена в ходе последнего рефакторинга расчетного блока (сейчас приоритет отдается большинству "1")

кроме того есть задача #292, которая должна решить эту дилемму на принципиальном уровне, т.е. позволять промоутеру для конкурса "оптимизировать" либо "пессимизировать" альтернативные оценки.
