### ISSUE TITLE
Алгоритм разбиения по заходам

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#232]
Подумать мне, какие условия надо прописать, что бы не получалось 9, 9, 9,2 человек по заходам.

Возможно ручное проставление?

**Comment by xfyre** [comment]
ручное нежелательно. разбивка по заходам - это такая вещь про которую лучше просто не думать в 9+9+9+2 нет большой беды, потому что ведущий вполне может самостоятельно сообразить, что последние 9+2 можно объединить.

**Comment by sashka-axis** [comment]
>> ведущий вполне может самостоятельно сообразить, что последние 9+2 можно объединить
Ведущий сообразит, но участники, уже видели эти листы и мысленно себя приписали к некоему воображаемому «заходу номер семь». 
У участников появляется некая модель наших действий — мы выстраивали участников ДНД за пределами зала и приглашали их туда объявлениями «участники седьмого захода, пройдите, пожалуйста на построение». А потом в итоге оказывается, что часть из них опаздала на своё построение изза того, что мы там сложили заходы.

**Comment by xfyre** [comment]
Я не вижу способа это автоматизировать. Можно сделать только индикацию вида "у вас фигня в последнем заходе", чтобы тот, кто занимается конфигурацией конкурсов, обращал на это внимание.
