### ISSUE TITLE
Печатные формы+ вывод на проектор

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#233]
Во-первых,

не нашла (вероятно ее нет) форму, в которой можно распечатать информацию по конкурсу, в частности, список номинаций с судьями, которые ее судят для ведущего.
Имею ввиду единый список по всем номинациям, а не для каждой номинации на Анонсе
Есть лист с табличкой (все номинации с турами и инициалы судей), но она неудобна к прочтению ведущим.

Во-вторых,
Вероятно стоит сделать форму (в том же перечне где анонс для судей) для вывода заходов на экран. Что бы подключить второй комп с проректором и там отображались участники и заходы.

**Comment by xfyre** [comment]
1) нужно нарисовать в Excel или Word, как она должна выглядеть
2) а что мешает просто вывести анонс для ведущего в отдельное окно на второй экран?
