### ISSUE TITLE
Выгрузка результатов АСХ

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#238]
При выгрузке никак не отражаются альтернативы.
Без них некорректное количество пар выводится в следующий тур.
Необходимо отображать их (возможно отдельным столбцом, или отдельной буквой) в файлах номинаций.

**Comment by xfyre** [comment]
так а как мне их показывать если оригинальным форматом их существование не предусмотрено?




нужно видимо с Денегиным это как-то решить?



—
