### ISSUE TITLE
Расчет скейтинга

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#243]
Надо проверить как отрабатывает скейтинг при следующих вводных данных (2 танца) для 1-2-3 мест

Пары  │                   │        │                   │        │                   │        │      │
  291   │ 2 2 1 1 2         │     1  │ 4 3 3 3 4       │     3  │                 │        │   03 │    1
  317   │ 1 1 2 2 6         │     2  │ 2 1 1 2 2       │     2  │                 │        │   02 │    2
  328   │ 4 5 3 4 4         │     3  │ 1 2 2 1 1       │     1  │                 │        │   01 │    3
  321   │ 5 4 5 3 3         │   4,5  │ 5 4 4 5 3       │     4  │                 │        │   04 │    4
  327   │ 3 3 4 5 5         │   4,5  │ 3 5 5 4 6       │     5  │                 │        │   05 │    5
  310   │ 6 6 6 6 1         │     6  │ 6 6 6 6 5       │     6  │                 │        │   06 │    6

Результаты программы dcalc указаны выше и ошибочны.
Необходимо поменять 2 и 3 место.

Комментарии от расчетчика из бальных (что б не потерялось)
"Смысл внедочитке всеми 11 правила. Там пар претендуют на 1 место по правилу 10 ы отдаем ту у которой 2 2 места. Оставшиеся 2 имеют по 1 первому. И переходят в 11 правило. По 11 правилу там 1е место посчитает правильно. А вот дальше в 11 правиле есть такая фраза "пока все рассматриваемые пары не получат места мы не можем перейти к рассмотрению других пар" это часто и опускают. По этой фразе вторая пара у которой 3 и 1 становится второй тк она осталась одна из рассматриваемых в 11 правиле а потом пара с 2 2 становится единственным претендентом на 3 место. А все с 11 правила определив там только 1 место ошибочно переходят к 10 и берут 2 оставшиеся пары как равных претендентов на 1 место"

**Comment by xfyre** [comment]
результат эксперимента: https://dl.dropboxusercontent.com/u/20971431/round322690_tech_results.pdf

то есть результаты тоже кривые

**Comment by xfyre** [comment]
Но, кстати, этот расчетчик неправ. Прямая цитата:

> в) в случае равенства коэффициентов эффективности и сумм их составляющих по оспариваемому и выше результатам необходимо сразу обращаться для разрешения спора пар к правилу №11, а не переходить к рассмотрению более низких результатов за танцы, как в правилах №№7 - 8.

именно это ситуация у нас имеет место выше (спор за 3 место с оценками 3-1 и 1-3).
поэтому мы должны сразу переходить к 11 правилу.

правило 10 указывает, что рассматриваются пары, имеющие хотя бы одну **рассматриваемую или выше** оценку:

> Оспариваемое место присуждается паре, занявшей большее количество раз рассматриваемый и выше результат в отдельных танцах - "коэффициент эффективности"

т.е. по правилу 10 (в моей интерпретации) пара с 2 вторыми местами исключается из рассмотрения на этапе перехода от расчета сумм (которые одинаковы - 1 + 3, 3 + 1, 2 + 2) к коэффициентам эффективности (которые будут 1, 1 и 0), и далее правило 11 может применяться только к парам имеющим 1 + 3 и 3 + 1.

само по себе правило 11 представляет собой просто скейтинг по всем оценкам, и в данном случае пара 291 (у которой 8 мест 1-3) выиграет у пары 328 (у которой 6 мест 1-3).

пара c двумя вторыми местами при этом окажется на 3 месте, что не очень логично (т.к. она имеет 9 мест 1-2, т.е. показывает результат лучший, чем 2 другие, по правилу 11).

соответственно, я бы сформулировал вопрос так: какие пары включаются в расчет по правилу 11?

варианты ответа:
- только те, которые мы не можем распределить по местам в соответствии с коэффициентом эффективности либо его суммой
- **все** пары с одинаковой суммой мест (включая те, которые имеют нулевой коэффициент эффективности, как в нашем примере пара 317)

первый вариант даст нам результаты 291 - 1, 328 - 2, 317 - 3
второй вариант даст результаты 317 - 1, 291 - 2, 328 - 3

как-то так
