### ISSUE TITLE
Search and transliteration problem

### ISSUE THREAD

**Issue by roman-tik** [danceconvention/dcnet-public#251]
I cannot find Cyrillic registrations using Latin charset. Its confusing because output is transliterated and thus misleading.

**Comment by roman-tik** [comment]
Thanks.
But I think it might be better a mapping.

Now there are:
TatК№yana
NatalК№ya
FrГ©dГ©rique
ZoltГЎn

**Comment by xfyre** [comment]
please provide screenshot 



—

**Comment by xfyre** [comment]
Looks like Excel UTF-8 problems doesn't allow to properly use export feature, especially on Mac.

CSV must be converted to cp1251 when website locale is set to RU and to latin1 for other languages.
