### ISSUE TITLE
add new state for booked registrations

### ISSUE THREAD

**Issue by fcastigliego** [danceconvention/dcnet-public#256]
it's necessary to have a quick view how many peoples need to give us difference, and send them a PATIAL PAYD email when we switch the state from APPROVED to PARTIAL PAYD or from PAYD to PARTIAL PAYD if they add competition after the first registration

the email message should be something like:
we received your partial payment, you will pay the remain part ath the door... bla bla bla

**Comment by xfyre** [comment]
This is reasonable, however it requires significant additions to the workflow. I'll be able to take care of it after FOWCS.

For now, as a workaround, you may use 'amount paid' column to sort them, however this won't be available for announces tool.

Upon recording a partial payment, user currently receives a email confirming that payment was made and mentioning that 'you have remaining amount of XXX pending'.

**Comment by fcastigliego** [comment]
for sure afther FO ;) 

i don't need this state to select in announces tool directly, but indirectly i need to select only pure APPROVED, in this moment a partially pay user is still APPROVED, that's all

**Comment by xfyre** [comment]
Maybe "Paid amount" filter in announces screen would be better?

**Comment by fcastigliego** [comment]
hmmm i don't know, some time if someone invoiced 150 but payd 20 euros for me is like, partially payd, i'm sure he will give me the rest at the door, i don't want bother the person with other unuseful advice email

**Comment by xfyre** [comment]
Implementation details:

- every pass will have an option to specify the minimum deposit amount
- if this option is specified in customer's pass and customer pays at least this amount (but doesn't pay full amount) registration is automatically transitioned to BOOKED state
- also, registration may be transitioned to BOOKED state manually, per promoter's decision
