### ISSUE TITLE
mass mail filter for period from registration

### ISSUE THREAD

**Issue by fcastigliego** [danceconvention/dcnet-public#257]
we would like to send mass email to users but we would like to send it just for registration older than 5 days or more, it's inappropriate to send a recall email for users registrated in the last day

**Comment by xfyre** [comment]
@fcastigliego I'm now working on fully integrating mass mail features with advanced search, so you'll be able to send specific emails to registrations selected by certain criteria.

Local example:

![Local example](http://monosnap.com/image/qz2jSqwLeIQBSCcHjh57ulv2zy64Wc.png)

**Comment by fcastigliego** [comment]
Wow wow wow it's really cool this interface! Power form me. If you can add
also a date range for registration it will be the best. We need to exclude
the most recent subscriber when we send the recall payment mass mail. I
know I'm demanding but a time range would be veru useful. Thank you
Il 29/mag/2015 20:05, "Ilya Obshadko" <notifications@github.com> ha scritto:

**Comment by xfyre** [comment]
That's what it's going to look like finally:

![Search Form](http://monosnap.com/image/p4Cq8hRVHpdKr943PBd3IdxXsiyTZX.png)

Looks good to you?

**Comment by fcastigliego** [comment]
I think is perfect! Definitely! Thank you... :)
Il 30/mag/2015 14:08, "Ilya Obshadko" <notifications@github.com> ha scritto:
