### ISSUE TITLE
impossible use the resend confirmation email tools for already registered users

### ISSUE THREAD

**Issue by fcastigliego** [danceconvention/dcnet-public#262]
last friday we sent mass email from my wordpress to 60 unpayd users to invite them to complete the payment, we choosed to use alternative delivery system because we believe that many peoples doesn't receive communication from dc-net.

i tried to register one of my fake users to the event and try to use the resend confimration email but if the user is already registered for other event the "resend confirmation message" tool doesn't work properly, the message is not true, the email should delivevered again 

![image](https://cloud.githubusercontent.com/assets/11611670/7590567/8e913eb2-f8c9-11e4-9e6d-e969be6f6881.png)

![image](https://cloud.githubusercontent.com/assets/11611670/7590586/a185c1be-f8c9-11e4-9e53-1ad45aa2cdc8.png)

**Comment by xfyre** [comment]
I have switched email delivery from Amazon SES to SendGrid. This should fix most delivery problems (please recheck with registrations that you consider problematic).

**Comment by xfyre** [comment]
The error message is indeed confusing, however. This account does exist, but confirmation message cannot be resent because account is already approved. I'll fix that.
