### ISSUE TITLE
add google analytics script (cross domain)

### ISSUE THREAD

**Issue by fcastigliego** [danceconvention/dcnet-public#276]
Opportunity to configure in event management information "UA-code" to permit to promoters that use GoogleAnalitycs on their web site to monitor the browsing and conversion, the script should be inject only if the ua-code is properly configured and only on the event pages

**Comment by xfyre** [comment]
@fcastigliego Does Google Analytics allow cross-domain usage? I'm not sure.

**Comment by fcastigliego** [comment]
yes, with special script i can give you, but anyway for the moment i would
prefer insert my goolge  id with standard google script to track it, even
it the tracking is not realted to my web site traffic

2015-05-26 17:08 GMT+02:00 Ilya Obshadko <notifications@github.com>:

**Comment by xfyre** [comment]
Google Analytics now supports cross-domain tracking without any additional scripts.

**Comment by fcastigliego** [comment]
yes,

UA-31560073-2

fantastic

2016-04-03 17:58 GMT+02:00 Ilya Obshadko <notifications@github.com>:
