### ISSUE TITLE
show pass name in list and change it

### ISSUE THREAD

**Issue by fcastigliego** [danceconvention/dcnet-public#280]
see in  list the pass option name, not only the price,  and possibility to change it quickly, without enter in the profile detail

**Comment by xfyre** [comment]
Current registrations list configuration is a "least common denominator" for all promoter requirements so far. It's not to be changed, but probably column list will be make configurable in a future.

**Comment by fcastigliego** [comment]
configurable columns report are the best choice so anyone can customize the
preferite view accordling with the role in the organization and probably it
would be better have just one report instead of two registration/payments,
with some more quick filters than the text search.

it's a common denominator just because is where all promoter and staff do
all the work during the months before event



2015-05-28 17:44 GMT+02:00 Ilya Obshadko <notifications@github.com>:
