### ISSUE TITLE
discount system management

### ISSUE THREAD

**Issue by fcastigliego** [danceconvention/dcnet-public#282]
for many commercial purpose we usually use discount codes, now we ask to write in comment the code ad then, when we receive the registration, we change the price manually and comunicate to the person that the discount is applyed, this workdlow slowdon the registration/payment process, the user send email after that to ask information about the discount and for promoter is an extra work,

many teachers ask it for their group or  we use it to targhet some specific people (people come from russia, people come form states or australia, discoutl for young people, discount for advanced or all star etc)

i propose this:
a list of discount campain where i can insert campain title, value (absolute value or percentage value), date expire

for each campain i would like to create mnemonic codes  or generate random code

when the user fill the registration form, write in a new field "promotional code" the code and press a button, if the code exist the discount title will appear and the discount will be applyed.

the user can pay without involve any promoter action

**Comment by xfyre** [comment]
@fcastigliego I need some clarifications on that. There are several priced items in registration to apply discounts to:
- pass
- various options
- contests

How do you want to handle this?

**Comment by fcastigliego** [comment]
i think that the most important is the pass, i don't think that the
discount  policy could be useful on option or contests fee, first of all
the software will bee too much complicate, and also becasue it can have a
reason if the discount is applyed by percentage, if it's applyed by fix
amount it doesn't matter

i think it's ok if we apply just on pass (for my management is ok, i don't
know for other promoters)

2015-06-20 18:31 GMT+02:00 Ilya Obshadko <notifications@github.com>:
