### ISSUE TITLE
search improvement

### ISSUE THREAD

**Issue by fcastigliego** [danceconvention/dcnet-public#284]
we have some search problem since we work a lot with foreign users

for example we are unable to find the users "Partos" because they have "Pártos" and in our italian keyboard web have just à, so tecnically we will have problem at the registration moment to find them.

i can suggest you a simple tecnic to emprove the search based on Q-GRAM system and you will have the similitude results too.

what you need is create a  long text field on database, a routine to normalize texts and activate the text search on your database if is not already activated.

the routine should do this:

lower case text, clean multiple blank spaces with single spaces, transform all accent char in flat char and split all the normalized tex in 3-GRAMS

example
"Pártos Attila" -> "par art rto tos att tti til ila"
save the qgrams in the new database fulltext indexed field

when i seach text "Patos attila" "or "attila patos" (note the R is missing) 
i will use the same rutine to normalize the search text  "pat ato tos att tti til ila" and i wil use te full search text provided form database to find the most 3grams occurrency and sort the results by rank

**Comment by xfyre** [comment]
I actually already do that for Cyrillic names. I could simply add another transliteration rule for Western alphabet.



—

**Comment by fcastigliego** [comment]
yes it woudl be useful, western alphabet would be very complicated  with
all the accent character we have :(

2015-06-04 13:27 GMT+02:00 Ilya Obshadko <notifications@github.com>:

**Comment by fcastigliego** [comment]
the transliteration solve also similitude problems? or bad typing problems?

2015-06-04 13:30 GMT+02:00 Francesco Castigliego <fcastigliego@gmail.com>:

**Comment by xfyre** [comment]
Of course transliteration can't correct mistakes. But it will create "plain" ASCII versions of all European names which simplifies the search.

**Comment by fcastigliego** [comment]
ok transliteration it's enought, take in consideration the q-gram tecnic
for the future, it helps a lot and save time when u search people's names
at the desk and the queue is long, i think is just extension of
transliteration

2015-06-05 18:02 GMT+02:00 Ilya Obshadko <notifications@github.com>:

**Comment by xfyre** [comment]
Closed by mistake.

**Comment by xfyre** [comment]
Now it's fixed
