### ISSUE TITLE
iframe auto resize

### ISSUE THREAD

**Issue by ofstudio** [danceconvention/dcnet-public#290]
Сделать чтобы размер iframe с регистрационной формой подстраивался под размер содержимого формы

https://github.com/davidjbradshaw/iframe-resizer
Кроссбраузерно, кроссдоменно.

Пример реализации: http://wcs.life/spring2015-online/
iframe с трансляцией и коментами подгружается с другого домена,

**Comment by xfyre** [comment]
Добавил загрузку "внутреннего" скрипта, если форма показывается в branded-режиме.

![Testing evidence](http://monosnap.com/image/1lPdtvIWElCHY3o2K8xJK97vZRLAH8.png)

**Comment by ofstudio** [comment]
http://westiefest.org/ru/2015/register/
Погонял в разных браузерах - работает корректно вроде.
Если не будет замечаний, выложу соотвествующий вариант "кода для вставки"

**Comment by xfyre** [comment]
ага, ok



—
