### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by ofstudio** [danceconvention/dcnet-public#308]
https://danceconvention.net/eventdirector/ru/runcontest/365352#selectResultsLink_results_tab

После завершения финалов Novice JnJ /  Zouk Glow Party при попытке распечатать результаты (топ3-топ5-… без разницы)  вместо pdf вижу страницу Доступ запрещен.

У меня есть доступ как у персонала (ofstudio@gmail.com). C Newcomer JnJ все было ок.

![screen shot 2015-10-24 at 23 03 50](https://cloud.githubusercontent.com/assets/2184504/10712434/efd97d0e-7aa3-11e5-8667-777a94c946ea.png)

**Comment by xfyre** [comment]
проверил локально, проблемы не увидел
там была ошибка с печатью результатов вообще (#309) - это починено и сегодня-завтра будет задеплоено
