### ISSUE TITLE
Registration status change (undo vs recover)

### ISSUE THREAD

**Issue by roman-tik** [danceconvention/dcnet-public#314]
An operator should have an option to change back the registration status if it was changed by mistake.
APPROVED > BOOKED > back to APPROVED

I would be totally fine if user does not get notified for one minute about the status change. And if there is another status change made - user gets notification about the last status only (if it is different from the one that was there one minute ago). In this way user does not get notified if I change the status back after mistake.

**Comment by xfyre** [comment]
In the meantime I have enabled the following transitions:
- BOOKED back to APPROVED
- PAID back to BOOKED

Those transitions do not result in any user notifications.
