### ISSUE TITLE
Изменение статуса партнерши от партнера

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#324]
Ситуация:
Ребята не берут пасс, но учатвуют в конкурсе.
В одной ПАРНОЙ номинации.
Т.е. партнер платит за партнершу.
У партнера при оплате статус меняется на paid, а вот у партнерши нет, хотя она ничего не должна.

Как хотелось бы: если у партнера указана партнерша, то после оплаты им номинации у нее появлялся статус "номинация оплачена партнером"

**Comment by xfyre** [comment]
мне пока кажется, что это лишняя ветка в логике. если партнерша ничего не должна, а в ситуации "номинация оплачивается партнером" это именно так и будет - у нее будет нулевая сумма инвойса. т.е. с точки зрения системы эта регистрация не будет неоплаченной.
