### ISSUE TITLE
Размер строк в бегунках

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#333]
Необходимо уменьшить высоту строк в бегунках.
Комфортно, когда на лист влезает порядка 40 участников.
Сейчас, так как реализован перенос целого захода на следующий лист, получалось что в ДнД на первых заходах на листе всего 20 участников, пол страницы пустые, а у судей 5 листов.

Вообще очень много макулатуры, так как мне ее месяц хранить и везти домой, то это почти пачка бумаги с такого конкурса (тяжело :( ). 

А главное смысл таких пространств не понятен, коммент пишется в длинну, да и сочинений я там не видела.

**Comment by xfyre** [comment]
вообще смысл в том, чтобы номера были хорошо видны на листе
