### ISSUE TITLE
Функция. Доплата на месте

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#334]
Может есть аналог, а я просто не нашла, но вот чего хочется:

Приходит товарищ с предоплаченным пассом, но не оплаченными номинациями,
или за ним какие еще долги, или он добавил какие-то номинации на месте.

Мы внесли все изменения в регистрацию, а потом надо нажать 5-6 кнопок, ввести сумму.

В такой момент очень хочется нажать кнопку "доплатил на месте", по которой автоматически впишется сумма разницы между оплатой и выставленной суммой.
А так же проставится коммент, что это "Оплата на месте" или "Оплата на кассе"
В идеале тут
![image](https://cloud.githubusercontent.com/assets/6746669/13913751/b5608f74-ef5a-11e5-8deb-eddbf718151b.png)

И возможно еще ее же дубль на закладке "Платеж" при выпаде выбора из кнопки "Действие"

**Comment by xfyre** [comment]
Реализация примерно такая:
https://monosnap.com/file/bfYcMOFLIRgUEAl4Khis2DnJaCmc4R.png
