### ISSUE TITLE
reg form option management additions

### ISSUE THREAD

**Issue by xfyre** [danceconvention/dcnet-public#346]
Needed for Italian Open:

- flag "option enabled by default"
- custom and separate email if several options are selected (for example if one of hotel rate are selected to user recipient as confirmation BCC to wcsitaly BCC to hotel)
- in the email the link to wise transfer should be different according to the RATE selected
- have a separate tab in registration process for hotel (minor)
- have CCS to customize the form (minor)

**Comment by fcastigliego** [comment]
item 2, is referenced to Rate option list, the email sent is only one, if i don't select at least 1 RATE i don't have hotel registration

i would like to add to make option group mandatory and have 
-- please select one item --
option 1 RATE 1 single room
option 2 RATE 2 twin room
option 3 RATE 2 double room
option 4 RATE 3 triple room 
NO HOTEL

if i select option "ho hotel" no email will be sent, if i select the others, email will be sent.
This will allow me to know exaclty who is registering to event without hotel because he choosed it, and not because he forget to select hotel 

about email customization, probably is better if i could have 3 templates:
option 1
option 2 and 3 (are similar email)
option 4

in this 3 different template i will be able to specify the correct Wise Transfer Link according to the rate selected. what do you think?

**Comment by xfyre** [comment]
@fcastigliego "NO HOTEL" selection doesn't seem to be a proper design choice. Instead, it's better just to clarify this via group description. For email, there's going to be a single template for special notification. All the conditions will be configured inside this template.

I'll create an initial version for you and you'll be able to adjust it as necessary.

**Comment by fcastigliego** [comment]
It's  important for me that the user select hotel or no hotel to be sure
that nobody miss this step. I would like to have a list of participants
that decided  don't use the hotel by purpose.
Il 17/Apr/2016 10:40, "Ilya Obshadko" <notifications@github.com> ha scritto:

**Comment by xfyre** [comment]
OK, I think I know how to implement this without compromising business
logic.

On Sun, Apr 17, 2016 at 2:01 PM, Francesco <notifications@github.com> wrote:

> It's important for me that the user select hotel or no hotel to be sure
> that nobody miss this step. I would like to have a list of participants
> that decided don't use the hotel by purpose.
> Il 17/Apr/2016 10:40, "Ilya Obshadko" <notifications@github.com> ha
> scritto:
>
> > @fcastigliego <https://github.com/fcastigliego> "NO HOTEL" selection
> > doesn't seem to be a proper design choice. Instead, it's better just to
> > clarify this via group description. For email, there's going to be a
> single
> > template for special notification. All the conditions will be configured
> > inside this template.
> >
> > I'll create an initial version for you and you'll be able to adjust it as
> > necessary.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/danceconvention/dcnet-public/issues/346#issuecomment-210977711
> >
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/danceconvention/dcnet-public/issues/346#issuecomment-211001002>
>



-- 
Ilya Obshadko

**Comment by xfyre** [comment]
So every option will have another additional flag "trigger special
notification".

When it's on and customer selects this option during registration - special
notification will be sent.
So you can add "no hotel" option and make selection mandatory, but enable
special notification only when some accommodation option was actually
selected.

Also it would be better to specify hotel options for 14/15/16/etc as "value
list" type attributes (not options).
This way you can show them only to customers who actually selected hotel
accommodation.


​

**Comment by xfyre** [comment]
All email customization should be done in SpecialNotification template using FreeMarker conditionals.

You can check option group and option IDs and display appropriate payment instructions etc.

**Comment by xfyre** [comment]
I have added an example to CustomSignupNotification template so you can set
up real payment links based on option IDs.
Please check FreeMarker conditionals syntax for more details.


On Sun, Apr 17, 2016 at 3:52 PM, Ilya Obshadko <xfyre@xfyre.com> wrote:

> So every option will have another additional flag "trigger special
> notification".
>
> When it's on and customer selects this option during registration -
> special notification will be sent.
> So you can add "no hotel" option and make selection mandatory, but enable
> special notification only when some accommodation option was actually
> selected.
>
> Also it would be better to specify hotel options for 14/15/16/etc as
> "value list" type attributes (not options).
> This way you can show them only to customers who actually selected hotel
> accommodation.
>
>
> ​
>



-- 
Ilya Obshadko
