### ISSUE TITLE
support of Carriage Return in 

### ISSUE THREAD

**Issue by fcastigliego** [danceconvention/dcnet-public#347]
the text with CR is rendered as flat line on the fornt end, this makes unreadable the text.

it should be possible write plain text, keeping CR and wite space or white line, someting like this:
-------------
 text demo text demo text demo
     - text demo
     - text demo

text demo
--------

![image](https://cloud.githubusercontent.com/assets/11611670/14524973/843f8456-023b-11e6-98aa-928bcc6ebd43.png)

**Comment by xfyre** [comment]
I will add markdown support to form hints for that.
