### ISSUE TITLE
Financial mismatches

### ISSUE THREAD

**Issue by roman-tik** [danceconvention/dcnet-public#351]
There is something wrong with invoices calculations.

http://joxi.net/l2ZlVwNs8yxGqr
http://joxi.net/MAjbM61uv3PDBA
http://joxi.net/ZrJdqwXu15jOd2
http://joxi.net/eAOR4w7S4K58j2
http://joxi.net/4Ak8OWpuM8wpkr
http://joxi.ru/brRQ8wlIQRlPwA
http://joxi.net/zANa5wDflLRz42

**Comment by xfyre** [comment]
I guess that at least some of them were somehow fixed. Mismatches were caused by previous inconsistencies in payment distribution algorithms. Root cause is already fixed.

Under this issue, additional invoice action was added ("Reprocess payments") to fix affected order items.
