### ISSUE TITLE
add columns to export

### ISSUE THREAD

**Issue by fcastigliego** [danceconvention/dcnet-public#357]
add IDUSER and REGISTRATION DATE to the export file

**Comment by xfyre** [comment]
What is IDUSER?
By "registration date" you mean the date when registration was finalized?

On Thu, Jun 30, 2016 at 12:19 PM, Francesco <notifications@github.com>
wrote:

> add IDUSER and REGISTRATION DATE to the export file
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/danceconvention/dcnet-public/issues/357>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AA7sDIBZlOe_wMMETmhSqUKMFnKM0qWDks5qQ4ougaJpZM4JB9iD>
> .
>



-- 
Ilya Obshadko

**Comment by fcastigliego** [comment]
2016-06-30 16:05 GMT+02:00 Ilya Obshadko <notifications@github.com>:

> What is IDUSER?
>
sorry, IDUSER is the user idetifier for  the event,

By "registration date" you mean the date when registration was finalized?
