### ISSUE TITLE
Выгрузка АСХ

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#413]
Привет.
Сколько ж меня тут не было)))

Я подумала и поняла, что для быстрой конвертации в файлы АСХ, мне достаточно минимума информации, при этом абсолютно не важно в каком формате она будет предоставлена. То есть мне проще взять отдельные таблички и скопировать их в обновляемые файлы АСХ, чем выгрузить готовые файлы АСХ и потом выискивать где ж те макросы, которые нужны Денегину, а мы не учли.

Я подготовила 3 формы, очень простые, все цветовые решения - условны и не обязательны. +/- строка мне не важна.

Сделай, пожалуйста. По срокам желательно так, что бы успеть протестировать до НордКапа.

Спасибо:) 
[Выгрузка АСХ.xlsx](https://github.com/danceconvention/dcnet-public/files/760216/default.xlsx)

**Comment by xfyre** [comment]
Ну это собственно тот концепт, который мы рассматривали с самого начала, но по какой-то причине решили сделать полноценно (видимо, отчасти еще и потому, что я рассчитывал что это разойдется по остальным конкурсам АСХ).

**Comment by UlianaP** [comment]
При учете сколько накрутили в файлах и что я там почти не слежу за изменениями и для АСХ надо только на НК - это лучший вариант.

**Comment by xfyre** [comment]
Вопрос такой - ты там абсолют в колонках классов не указала осмысленно или просто забыла?

**Comment by UlianaP** [comment]
1. Абсолют нужен, добавь, пожалуйста, если еще не.
2. точно можно и нужно удалить поле "Информация о счетной комиссии" на закладке "Отчет - Ассоциация спортивного хастла". Сейчас туда просто ставлю любое значение, но периодически забываю и отвлекаюсь

По самому формату выгрузки замечаний нет. Все отлично

Вопросы.
1. Есть ли сейчас обновление данных танцоров (классы), по данным базы АСХ? Для проверки перед стартом в правильной ли номинации человек.
2. Тестировала только по закрытому конкурсу, а если конкурс будет в процессе (например, прошла 1/8 и 1/4 только) все так же отработает?

**Comment by xfyre** [comment]
По вопросам:
1. Да, база обновляется и все проверки живые, это не менялось с прошлого года.
2. Теоретически все должно быть нормально, хотя я не проверял этот случай.

По остальному:
1. Абсолют добавил.
2. Поле удалил - оно действительно теперь не нужно.

Мелкий нюанс: если конкурс был "только финалы", файл выгружается нормально, но Excel по какой-то причине говорит, что он требует починки, чинит его и открывает как обычно.
