### ISSUE TITLE
Порядок судей

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#415]
Не критично, но в Анонсе для ведущего судьи выводятся хаотично и в этом хаотичном порядке ведущий выстраивает судей для демонстрации оценок.
Что бы записывать оценки на слух удобнее, что бы судьи сидели в том порядке, в каком они идут в области проставления оценок.

Если это долго и сложно реализовывать можно забить и закрыть задачу.

**Comment by xfyre** [comment]
пофиксил. понятно что тут будет нюанс: в стандартном WSDC-шном JnJ, когда судьи на партнеров и партнерш раздельно, сортировка будет соблюдаться, но при этом сами вкладки ввода будет содержать разные наборы инициалов.
