### ISSUE TITLE
Чекин партнерш по партнеру

### ISSUE THREAD

**Issue by UlianaP** [danceconvention/dcnet-public#416]
Еще один момент.

Если партнерша участвует только в парной номинации и без пасса, то у нее нет конверта, соответственно, когда она приходит, отметка о том, что она присутствует нигде не происходит. 

А так как сумма у нее 0, то и денег не надо вносить, она остается в состоянии "Апрув"

По идее по партнеру надо проверять партнершу и если она без номер чекинить их вместе.

**Comment by xfyre** [comment]
это очень нестандартная ситуация: на подавляющем большинстве ивентов опции "без пасса" не существует, т.е. даже если партнерша выходит только в стриктли или классик - она все равно должна оплатить пасс и пройти регистрационную стойку.

поэтому таких нужно просто проверять по спискам номинаций и уточнять.
