### ISSUE TITLE
policy change on order results in crash after special cancellation

### ISSUE THREAD

**Issue by xfyre** [danceconvention/dcnet-public#432]
if special price was already paid and requires refund, an attempt to change order policy results in a crash

- an error needs to be fixed
- we need to provide a warning about refunding cancelled items

**Comment by xfyre** [comment]
This is a symptom of a larger problem. Discount application now works with registration items (vs ordered items) and discount doesn't respect "order state" (currencies, policies, etc.)

Even if we fix discount application (which is technically possible) - that doesn't help us to fix discount removal (we don't have enough information to restore the previous state of things).

One possible solution to this would be moving discount logic to order processing, when we are calculating registration price and creating invoices.

**Comment by xfyre** [comment]
cc: @roman-tik 

The issue is fixed, however I still recommend to avoid complex multi-currency setups in general. They are difficult to manage and may produce various edge cases that are prone to human error.

**Comment by roman-tik** [comment]
This is dictated by the business nature. People expect the flexibility in terms of the currency they pay with. This is not an individual case unfortunately. So we have to allow multi currency payment to improve customer experiences
