### ISSUE TITLE
Pass - Option - Attribute UI Bug 

### ISSUE THREAD

**Issue by ofstudio** [danceconvention/dcnet-public#437]
**Задача**: для одного из пассов нужно сделать _обязательное_ дополнительное поле типа String

Я создаю соотв обязательный атрибут и опцию для этого пасса. 

**Проблема**: 
1. опция показывается для первого пасса в списке. 
2. Опция показывается для нужного пасса, но с  галочкой: выбрана, но можно выделение снять (тогда как опция для пасса строго обязательна).

**Comment by ofstudio** [comment]
Аттрибут

![screen shot 2017-11-07 at 13 46 01](https://user-images.githubusercontent.com/2184504/32490392-1b65f16c-c3c4-11e7-9005-e4045977db7d.png)

**Comment by ofstudio** [comment]
Опция

![screen shot 2017-11-07 at 13 49 15](https://user-images.githubusercontent.com/2184504/32490403-28f605a6-c3c4-11e7-99d5-aa7baf4978e5.png)


![screen shot 2017-11-07 at 13 49 20](https://user-images.githubusercontent.com/2184504/32490414-30a44146-c3c4-11e7-9f15-2e7a8be26b9a.png)

![screen shot 2017-11-07 at 13 49 26](https://user-images.githubusercontent.com/2184504/32490420-354f015e-c3c4-11e7-9145-1cb7f040c54f.png)

**Comment by ofstudio** [comment]
Поведение: https://www.youtube.com/watch?v=ohEo_Oa1khg&feature=youtu.be

**Comment by ofstudio** [comment]
Ожидаемое поведение

![dconv ui bug expected](https://user-images.githubusercontent.com/2184504/32491075-5ef41dc6-c3c6-11e7-921a-9ecc95d1a2d5.gif)

**Comment by xfyre** [comment]
проблема (1) у меня не воспроизвелась

что касается проблемы (2) - обязательность _значения_ атрибута не всегда означает обязательность _наличия_ опции (пример - регистрация на Winter White, там можно указать партнера, а можно и не указывать).

**Comment by xfyre** [comment]
очевидный workaround для этого сценария следующий: сделать не опцию, а группу опций с обязательным указанием значения, сделать в группе ровно одну опцию, и вот к этой опции уже привязать атрибут. тогда оно будет работать ожидаемым образом.

**Comment by xfyre** [comment]
более глобальное решение проблемы - это разрешить привязывать атрибут к любому типу billalbe item (пассу, опции либо даже конкурсу). я сделаю это отдельно.
