### ISSUE TITLE
Misleading due date

### ISSUE THREAD

**Issue by ofstudio** [danceconvention/dcnet-public#469]
Участник зарегистрировался за 2 дня до окончания ценовой политики `Early`, но в письме получил уведомление, что оплатить можно в течение 10 дней (в соотв с настройками `Срок оплаты счета`)

![31955877_10209686785526945_342815995984871424_n](https://user-images.githubusercontent.com/2184504/39701846-618e8c3c-520b-11e8-879c-7c5ef99aa86b.jpg)

![screen shot 2018-05-07 at 15 22 59](https://user-images.githubusercontent.com/2184504/39701851-66e5710a-520b-11e8-8d99-707906c0aaf8.png)

![screen shot 2018-05-07 at 15 24 52](https://user-images.githubusercontent.com/2184504/39701854-6e33e0a4-520b-11e8-9a05-6553205db67a.png)

![screen shot 2018-05-07 at 15 25 57](https://user-images.githubusercontent.com/2184504/39701869-7ec61fd6-520b-11e8-8a10-133fa8e88dc9.png)

Возможные варианты решения

1. (минимально) В интерфейсе настроек дать промоутеру информацию, что ценовая политика применяется по дате регистрации. Тк сейчас насколько я могу судить это реализовано именно так, хотя в реальной жизни обычно ценовая политика фиксируется по факту оплаты/депозита.

2. (максимально) Фиксировать ценовую политику по дате оплаты / депозита (либо сделать это настраиваемым) и проставлять соотв дату в уведомлении

**Comment by xfyre** [comment]
п.1 на самом деле присутствует, правда в виде настройки "expire policy unless registration is paid". со стороны участника, как только политика заэкспайрилась, вылезает предупреждение про pricing policy is expired, please contact event promoter.

что касается п.2 - хотелось бы лучше понимать что такое "фиксировать". например: я могу при генерации инвойса выставлять ему due date в соответствии с политикой, если политика кончается раньше, чем выдается дней для оплаты по умолчанию.

**Comment by ofstudio** [comment]
> например: я могу при генерации инвойса выставлять ему due date в соответствии с политикой, если политика кончается раньше, чем выдается дней для оплаты по умолчанию.

это будет более логично.
