### ISSUE TITLE
Missing competitor's name blurring in Total Tie Break report

### ISSUE THREAD

**Issue by ofstudio** [danceconvention/dcnet-public#522]
https://danceconvention.net/eventdirector/en/roundscores/6615823.pdf

<img width="261" alt="Screenshot 2021-02-08 at 20 01 33" src="https://user-images.githubusercontent.com/2184504/107254857-c4fc7100-6a48-11eb-8c80-2ae49458fdd9.png">

**Comment by xfyre** [comment]
Fixed & deployed
