### ISSUE TITLE
Add QR-code payment option according to Russian ГОСТ Р 56042-2014

### ISSUE THREAD

**Issue by ofstudio** [danceconvention/dcnet-public#523]
Add QR-code payment option in addition to Russian PD4 Payment Form (which is quite useless this time).

The structure of QR is described in the national ГОСТ Р 56042-2014 and it's quite simple: payment data serialized into a string (see working example below).

This kind of QR codes is supported by all major Russian banks mobile applications (except Sber). The client process is very simple and convenient comparing to manual entering of all payment details.

## Example
```js
const fs = require('fs')
const qr = require('qr-image')
const Iconv = require('iconv').Iconv
const toWin1251 = new Iconv('utf-8', 'windows-1251')
const toKoi8R = new Iconv('utf-8', 'koi8-r')

/**
 * @typedef {Object} Payment
 * @property {string} Name - наименование получателя платежа
 * @property {string} BIC - БИК банка получателя платежа
 * @property {string} BankName - наименование банка получателя платежа
 * @property {string} CorrespAcc - корреспондентский счет банка получателя платежа
 * @property {string} PersonalAcc - счет получателя платежа
 * @property {string} PayeeINN - ИНН получателя платежа
 * @property {string} KPP - КПП получателя платежа либо 0, если неизвестен
 * @property {string} Purpose - назначение платежа
 * @property {number} Sum - сумма платежа в копейках
 */
const payment = {
  Name: 'Индивидуальный Предприниматель Авласевич Екатерина Ивановна',
  BIC: '044525225',
  BankName: 'ПАО СБЕРБАНК',
  CorrespAcc: '30101810400000000225',
  PersonalAcc: '40802810338120004788',
  PayeeINN: '370214319238',
  KPP: '0', // Ноль, если неизвестен. У ИП нет КПП
  Purpose: 'Оплата за участие в Russian Open WCS Championship 2021 REG 6185730/1102',
  Sum: 630000, // Сумма в копейках!
}


const qrContent = encodeGost56042(payment)
fs.writeFileSync('QR.png', qr.imageSync(qrContent, {type: 'png'}))



/**
 * Формирование содержимого QR-кода для оплаты по банковским реквизитам по ГОСТ Р 56042-2014
 * https://files.stroyinf.ru/Data2/1/4293771/4293771168.htm
 *
 * @param {Payment} payment - данные платежа
 * @param {Object} opts - опции
 * @param {number} opts.codePage - кодировка: 1 = win-1251, 2 = utf-8, 3 = koi8-r
 * @returns {Buffer}
 */
function encodeGost56042(payment, opts = {}) {

  // Default codepage win-1251. This will produce smaller QR payload compared to utf-8
  const codePage = opts.codePage || 1
  let result = `ST0001${codePage}`
  for (let field in payment) {
    result += `|${field}=${payment[field]}`
  }

  console.log(result)
  result = Buffer.from(result)

  switch (codePage) {
    case 1: // win-1251
      result = toWin1251.convert(result)
      break
    case 2: // utf-8
      break
    case 3: // koi8-r
      result = toKoi8R.convert(result)
      break
    default:
      throw new RangeError('Invalid CodePage')
  }

  return result
}
```

## Result
QR payload (win-1251 encoding used):

`ST00011|Name=Индивидуальный Предприниматель Авласевич Екатерина Ивановна|BIC=044525225|BankName=ПАО СБЕРБАНК|CorrespAcc=30101810400000000225|PersonalAcc=40802810338120004788|PayeeINN=370214319238|KPP=0|Purpose=Оплата за участие в Russian Open WCS Championship 2021 REG 6185730/1102|Sum=630000`

![payment sample](https://user-images.githubusercontent.com/2184504/111616885-7a160c00-87f3-11eb-9b4e-c9dbc5f870da.jpg)

**Comment by xfyre** [comment]
@ofstudio Is using cp1251 mandatory? Or it's still possible to use UTF-8?

**Comment by ofstudio** [comment]
@xfyre it's absolutely ok to use utf-8

The only thing this will produce a larger payload (due to 2 bytes per Cyrillic symbol in utf-8) and a larger QR image.

**Comment by xfyre** [comment]
@ofstudio Got it. It's doable both ways of course.

**Comment by xfyre** [comment]
@ofstudio Is there any way to verify generated QR code?

**Comment by ofstudio** [comment]
@xfyre As far as I know there is no dedicated test environment for testing such QRs. 

You will need a mobile app and an account of any major Russian bank (excluding Sber) to test this

I can perform tests: pm me samples of QR codes
