### ISSUE TITLE
Permanent Offline statusbar in Safari

### ISSUE THREAD

**Issue by ofstudio** [danceconvention/dcnet-public#525]
<img width="482" alt="Screenshot 2022-11-01 at 11 56 26" src="https://user-images.githubusercontent.com/2184504/199196987-dd836400-c457-4ed8-b114-a33fe147942e.png">

Status "offline" is constantly displayed in Safari, macOS

Chrome is fine

**Comment by xfyre** [comment]
Fixed in danceconvention/dcnet-nuxt@bfc5958a
