### ISSUE TITLE
Unable to dismiss canceled event notification

### ISSUE THREAD

**Issue by ofstudio** [danceconvention/dcnet-public#529]
Step 1
<img width="752" alt="Screenshot 2023-04-26 at 11 29 34" src="https://user-images.githubusercontent.com/2184504/234517533-81e74079-bfb5-4af4-b265-eb37cba1e422.png">

Step 2
<img width="595" alt="image" src="https://user-images.githubusercontent.com/2184504/234517675-ffb7cbe2-4071-47ff-aa5f-8849fc819eb3.png">

**Comment by xfyre** [comment]
In this case it's basically a responsibility of the event promoter to invalidate and remove unconfirmed registrations (which I just did)
