### ISSUE TITLE
Event signups and divisions are visible to the public even if they are disabled in the settings

### ISSUE THREAD

**Issue by ofstudio** [danceconvention/dcnet-public#532]
example 

https://danceconvention.net/eventdirector/ru/eventpage/7608522-stpetersburg-wcs-nights-2023/divisions

https://danceconvention.net/eventdirector/ru/eventpage/7608522-stpetersburg-wcs-nights-2023/signups

**Comment by xfyre** [comment]
Fix will be deployed today
